### ISSUE TITLE
[DG] Final fixes megathread

### ISSUE THREAD

**Issue by immanuelhume** [AY2223S2-CS2103T-W14-1/tp#321]
- [x] Keyboard interactions should be before command handling #322 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/47441677/230840551-0600556f-852b-490a-becb-c50b7141bf26.png">

- [x] Line separation between H2 blocks are missing #322 
- [x] This diagram is too smal #322 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/47441677/230841242-f94b3fb8-711e-4c07-920c-ff4452833d0f.png">

- [x] This diagram is a bit small #322 
<img width="571" alt="image" src="https://user-images.githubusercontent.com/47441677/230841900-005e723a-681a-424c-8236-f68e770cbfb9.png">

- [x] Missing enumeration of all the commands available
- [x] Missing disclaimer for lifeline not ending
- [x] No explanation for role of `IsSame`
- [x] Stray '1' character
<img width="555" alt="image" src="https://user-images.githubusercontent.com/47441677/230873771-29708fca-34c3-40f3-81ad-0efb409cb8d1.png">
